# Generated by Django 5.2.1 on 2025-06-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebookentry',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Pieces', 'Pieces'), ('Boxes', 'Boxes'), ('kg', 'kg'), ('g', 'g')], default='Pieces', max_length=100),
        ),
    ]
