# Generated by Django 5.2.1 on 2025-06-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_remove_notebookentry_unit_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_per_unit',
            field=models.CharField(default=1, max_length=100, verbose_name=str),
        ),
    ]
