# Generated by Django 5.2.1 on 2025-06-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_product_price_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookentry',
            name='quantity',
            field=models.FloatField(default=1, max_length=10000, verbose_name=float),
        ),
    ]
