# Generated by Django 5.2.1 on 2025-06-10 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0004_alter_notebookentry_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpendingMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.product')),
            ],
        ),
    ]
