# Generated by Django 5.2.1 on 2025-06-10 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0001_initial'),
        ('suppliers', '0005_alter_product_price_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspendingmonthly',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productspendingmonthly',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_spending', to='suppliers.product'),
        ),
    ]
