# Generated by Django 5.2.1 on 2025-06-12 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0002_productspendingmonthly_cost_and_more'),
        ('suppliers', '0005_alter_product_price_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspendingmonthly',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productspendingmonthly',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productspendingmonthly',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productspendingmonthly',
            unique_together={('product', 'month', 'year')},
        ),
    ]
