# Generated by Django 5.2.1 on 2025-06-12 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0003_productspendingmonthly_month_and_more'),
        ('suppliers', '0005_alter_product_price_per_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpendingYearly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.product')),
            ],
            options={
                'unique_together': {('product', 'year')},
            },
        ),
    ]
